### ISSUE TITLE
Implementar React Router Dom y estilar Navbar

### ISSUE THREAD

**Issue by achtur** [jaumeserr/Skyscanner-Nuclio#36]
Necesario para poder acceder a flightListPage desde Home

**Comment by achtur** [comment]
**Branch: Trabajar en ruth/#36-RRD !**

Luis continúa la implementación:

- /  (=== home)
- /flights
- /login
- /register

**Comment by LuiAlvarez** [comment]
Pasos siguientes a seguir

- Posición de botones (Flexbox)
- Revisar márgenes 
- Colores de logo UserInfo
- Añadir las NavBar en Login, Register y UserInfo
